name: 'My Docker Composite Action'
description: 'Performs tasks using Docker'
inputs:
  org:
    description: 'The GitHub organization'
    required: true
  repo:
    description: 'The GitHub repository'
    required: true
  github_token:
    description: 'The GitHub access token'
    required: true
  branch_name:
    description: 'The branch name to work with'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    ORG: ${{ inputs.org }}
    REPO: ${{ inputs.repo }}
    GH_TOKEN: ${{ inputs.github_token }}
    BRANCH_NAME: ${{ inputs.branch_name }}