name: 'NotifyJobStatus'
description: 'Retrieve the workflow job status for the unit test job or any other job to send slack notification'
inputs:
  GH_PROJECT_ORGNAME:
    description: 'The GitHub organization'
    required: true
  GH_PROJECT_REPONAME:
    description: 'The GitHub repository'
    required: true
  RUN_ID:
    description: 'The Current workflow run _id'
    required: true
  JOB_NAME_1:
    description: 'The Workflow job name_1'
    required: true
  JOB_NAME_2:
    description: 'The Workflow job name_2'
    required: false
  CHANNEL_ID:
    description: 'Provide Slack channel Id to send notification'
    required: true
  SLACK_BOT_TOKEN:
    description: 'Slack bot token'
    required: true
  CUSTOM_LINK:
    description: 'Custom link true or false'
    default: 'false'
    required: true
  NEW_LINK_JOB_NAME:
    escription: 'new job name'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
