name: 'Get-workflow-Job Status'
description: 'Retrieve the workflow job status for the unit test job or any other job'
inputs:
  ORG:
    description: 'The GitHub organization'
    required: true
  REPO:
    description: 'The GitHub repository'
    required: true
  RUN_ID:
    description: 'The Current workflow run _id'
    required: true
  # JOB_NAME:
  #   description: 'The Workflow's job name'
  #   required: true
runs:
  using: 'docker'
  image: 'Dockerfile'