name: 'GetJobStatus'
description: 'Retrieve the workflow job status for the unit test job or any other job'
inputs:
  ORG:
    description: 'The GitHub organization'
    required: true
  REPO:
    description: 'The GitHub repository'
    required: true
  RUN_ID:
    description: 'The Current workflow run _id'
    required: true
  JOB_NAME_1:
    description: 'The Workflow job name_1'
    required: true
  JOB_NAME_2:
    description: 'The Workflow job name_2'
    required: false
  CHANNEL_ID:
    description: 'Slack channel Id'
    required: true
  SLACK_BOT_TOKEN:
    description: 'Slack bot token'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'